stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch: {}
notification:
  recipients:
  - recipient: "1"
    notifier: local:n-5x5ws
  condition:
  - Success
  - Changed
  - Failed
