stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/rancher
        ln -s `pwd` /go/src/github.com/rancher/pipeline-example-go
        cd /go/src/github.com/rancher/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
      cpuRequest: 100m
      cpuLimit: 100m
      memoryRequest: 100M
      memoryLimit: 100M
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
      cpuRequest: 100m
      cpuLimit: 100m
      memoryRequest: 100M
      memoryLimit: 100M
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
